article/urls.py
from django.contrib import admin
from django.urls import path
from article import views
from . import views

app_name = "article"
urlpatterns = [
    path('dashboard/', views.dashboard, name= "dashboard"),
    path('addarticle/', views.addArticle, name= "addarticle"),
    path('article/<int:id>/', views.detail, name= "detail"),
    path('edit/<int:id>/', views.editArticle, name= "edit"),
    path('delete/<int:id>/', views.deleteArticle, name= "delete"),
    path('', views.articles, name= "articles"),
    path('comment/<int:id>/', views.addComment, name= "comment"),



]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from article import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
#from article import views
from . import views

app_name = "user"
urlpatterns = [
    path('register/', views.register, name= "register"),
    path('login/', views.loginUser, name= "login"),
    path('logout/', views.logoutUser, name= "logout"),

]

templates/includes/navbar.html
<!--  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">  -->

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">PastaCow Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About Me</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
          </li>

        </ul>

        <ul class="navbar-nav ml-auto">

        {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:dashboard' %}">Control Pannel</a>
          </li> 

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
          </li>  



        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
          </li> 
        {% endif %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
          </li>   

  

   

        </ul>

      </div>
</nav>

templates/includes/posttemplate.html
 <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Single comment-->
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>