article/urls.py
from django.contrib import admin
from django.urls import path
from article import views
from . import views

app_name = "article"
urlpatterns = [
    path('dashboard/', views.dashboard, name= "dashboard"),
    path('addarticle/', views.addArticle, name= "addarticle"),
    path('article/<int:id>/', views.detail, name= "detail"),
    path('edit/<int:id>/', views.editArticle, name= "edit"),
    path('delete/<int:id>/', views.deleteArticle, name= "delete"),
    path('', views.articles, name= "articles"),
    path('comment/<int:id>/', views.addComment, name= "comment"),



]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from article import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE) # if user is deleted cascade deletes all the info about user
    title = models.CharField(max_length=50)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True) #this automatically gets the date 
    article_image = models.FileField(blank = True, null = True, verbose_name="Add pictures to the article")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ["-created_date"]


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Article", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="Name")
    comment_content = models.CharField(max_length=200, verbose_name="Comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ["-comment_date"]

article/forms.py
from django import forms
from django.forms import fields
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]

article/views.py
import article
from django.shortcuts import get_list_or_404, render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment

from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request, "articles.html", {"articles":articles})
    else:
        articles = Article.objects.all()
        return render(request, "articles.html", {"articles": articles} )

def index(request):
    #return HttpResponse("<h3> Main Page</h3>")
    return render(request, "index.html", {"number": 7})


def about(request):
    return render(request, "about.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)  

@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit= False )
        article.author = request.user
        article.save()
        messages.success(request, "You successfully created an article!")

        articles = Article.objects.filter(author = request.user)
        context = {
            "articles": articles
        }
        return render(request,"dashboard.html", context) 

    return render(request, "addarticle.html", {"form":form}) 

def detail(request, id):
    #article =  Article.objects.filter(id = id).first()
    article =  get_object_or_404(Article, id = id)
    comments = article.comments.all()
    return render(request, "detail.html", {"article": article, "comments":comments})

@login_required(login_url="user:login")
def editArticle(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit= False )
        article.author = request.user
        article.save()
        messages.success(request, "You successfully updated the article!")

        articles = Article.objects.filter(author = request.user)
        return render(request, "dashboard.html", {"articles": articles})

    return render(request, "edit.html", {"form":form})

@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    deleted_title = article.title
    article.delete()
    messages.success(request, "You successfully deleted the article titled:  \"  " + str(deleted_title) + " \"")
    return redirect("article:dashboard")


def addComment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        new_comment = Comment(comment_author = comment_author, comment_content= comment_content)
        new_comment.article = article
        new_comment.save()
    #return redirect("/articles/asdf/" + str(id))
    return redirect(reverse("article:detail", kwargs={"id":id}))

templates/about.html
{% include "layout.html" %}

{% block body %}

<h3 style = "margin-left : 50px;"> About Me  </h3>
<hr>

<p style = "margin-left : 50px;"> Add things about me </p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <h3>Write an Aritcle </h3>
            <br>   
            <form method = "post" enctype="multipart/form-data" > 
                {% csrf_token %}
                {{form | crispy}}
                {{form.media}}
                
                <button type = "submit" class = "btn btn-danger"> Add </button>
             </form>
        </div>
    </div>



{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class = "col-lg-8">
            <h3> Articles </h3>
            <hr>
        </div>
    </div> 
</div> 


<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class = "col-lg-8">
            <form>
                {% csrf_token %}
                <input type = "text" name ="keyword" class = "input sm" maxlength="64" placeholder="Go...">
                <button type = "submit" class="btn btn-danger"> Search </button>
                <br>
            </form>
        </div>
    </div> 
</div> 






{% if articles %}

{% for article in articles  %}
 <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
            <div class="col-md-10 offset-md-3">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a href = "{% url 'article:detail' article.id %} "> <h3 class="fw-bolder mb-1"> {{article.title}} </h3> </a>
                            <div class="text-muted fst-italic mb-2">by {{article.author.username}} </div>
                            <hr>
                            <p>{{article.created_date}} </p>
                            <hr>
                        </header>

                        {% if article.article_image %}
                        <!-- Preview image figure -->
                             <a href = "{% url 'article:detail' article.id %} "> <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure> </a>
                        {% endif %}
                         <!--Post content--> 
                        <p class= "lead">
                        {{article.content | safe |truncatewords:30}}
                        </p>
                        <a style = "float : right" href = "{% url 'article:detail' article.id %} " class = "btn btn-danger"> Read More </a>
                        <br><br><hr>
 
                    </article>
                </div>   
                </div> 
            </div>
        </div>
{% endfor %}
{% else %}


<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class = "col-lg-8">
            <div class= "alert alert-danger"> 
                No articles found!
            </div>  
        </div>
    </div> 
</div> 


{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3> Control Pannel </h3>
<hr>
<p>
 Welcome, <small> {{request.user.username}} </small> !
</p>
<hr>

<a class="btn btn-danger" href="{% url 'article:addarticle' %}" > Add Article </a> 
<hr>

{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>


  </thead>
  <tbody>
  {% for article in articles  %}
      <tr>
      <th scope="row"> {{article.id}} </th>
      <td> <a href = "{% url 'article:detail' article.id %} "> {{article.title}}  </a> </td>
      <td>{{article.author.username}}</td>
      <td>{{author.date_created}}</td>
      <td> <a href = "{% url 'article:edit' article.id %} " class = "btn btn-danger"> Edit</a> </td>
      <td> <a href = "{% url 'article:delete' article.id %} " class = "btn btn-danger"> Delete</a> </td>
    </tr>
  
  {% endfor %}


  </tbody>
</table>
{% else %}
<div class = "alert alert-danger">
You do not have an article yet...
</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h3 class="fw-bolder mb-1"> {{article.title}} </h3>
                            <div class="text-muted fst-italic mb-2">by {{article.author.username}} </div>
                            <hr>
                            <p>{{article.created_date}} </p>
                            <hr>

                        </header>

                        {% if article.article_image %}
                            <!-- Preview image figure -->
                            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
     
                        {% endif %}

                         <!--Post content--> 
                        <p class= "lead">
                        {{article.content | safe}}
                        </p>
 
                    </article>

                    <!-- Comments section
                    <form>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input name = "comment_author" class="form-control"  placeholder="Enter your name...">
                            <small id="emailHelp" class="form-text text-muted"></small>
                        </div>
                    </form>

                    <section class="mb-5">
                    
                        <div >
                            <label for="exampleInputEmail1">Comment</label>
                            <!-- Comment form-
                            <form method = "post" action = "{% url 'article:comment' article.id %}" class="mb-4">
                                <textarea name ="comment_content" class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea>
                                    {% csrf_token %}                            
                                    <button type="submit" class = "btn btn-primary"> Add Comment </button>
                                </form>
                        <div class="d-flex mb-4"></div> 
            
                    </section> -->

                    <h4> Comments </h4>
                    {% if comments %}
                    {% for comment in comments  %}
                         <div class= "media mb-4">
                            <img class="d-flex mr-3 rounded-circle" src ="http://placehold.it/50x50"> <img>
                            <div class = "media-body">
                                <h5 class = "mt-0"> {{comment.comment_author}} </h5>
                                {{comment.comment_date}}
                                <br>
                                {{comment.comment_content}}      
                                <br>                             
                            </div>
                        </div>
                    {% endfor %}

                    {% else %}
                    <div class= "alert alert-danger"> 
                        Be the first one to comment on this article!
                    </div>

                    

                    {% endif %}
                    <br><br>

                        <h5 > Make a Comment </h5>
                        <div >
                            <form action = "{% url 'article:comment' article.id %}" method = "POST">
                                {% csrf_token %}
                                <div class = "form-group">
                                    <label > Name </label>
                                    <input name = "comment_author" type = "text" class = "form-control" >
                                </div>

                                <div class = "form-group">
                                    <label> Comment </label>
                                    <textarea name= "comment_content" class = "form-control" rows="3"  placeholder= "Leave a comment here..."></textarea>
                                </div>
                                <button type="submit" class = "btn btn-primary"> Add Comment </button>
                            </form>
                         </div>
               
                     
               
                </div>    
            </div> 
        </div>      
{% endblock  %}

templates/edit.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <h3>Edit Your  Aritcle </h3>
            <br>   
            <form method = "post" enctype="multipart/form-data" > 
                {% csrf_token %}
                {{form | crispy}}
                {{form.media}}
                
                <button type = "submit" class = "btn btn-danger"> Update </button>
             </form>
        </div>
    </div>



{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}


    <div class= "jumbotron text-center"> 
    <h3> Welcome to My Blog</h3>
    <p> 
        This is where I share my thoughts and experiences about Computer Science, Economics and (sometimes) politics.
        I am by no means a professional, but I am aspiring to be one. Here I plan to write about the things I find interesting such as
        the books I read, lessons I learn, my thoughts on recent economic and financial news, science, new technologies and startups. 
        
        I also plan on writing about my investment experiences which I started around February 2021.

    </p>
    </div>
    
    {% if request.user.is_authenticated %}
    Welcome,  {{request.user.username}}
    
    {% else %}
    Not logged in!
    {% endif %}

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!--
        
        <link rel="stylesheet" href = "{% static 'css/bootstarp.min.css' %}" > 
    -->
    <title>Practice Blog</title>
</head>
<body>

    {% include "includes/navbar.html" %}

    <div style = "margin-top : 100px; margin-bottom : 75px" class="container">

    {% if messages %}
    {% for message in messages %}
        {% if message.tags == "info" %}
        <div  class="alert alert-danger">{{ message }}</div>
        {% else %}
        <div  class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}

{% endif %}

        {% block body %}

        
        {% endblock body %}
    </div>

    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>


    <!-- 
    <script src = "{% static 'js/jquery-3.6.0.min.js' %}"> </script> 
    <script src = "{% static 'js/bootstrap.min.js' %}"> </script> 
    -->
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}




    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <h3>Log in Here </h3>
            <br>   
            <form method = "post" > 
                {% csrf_token %}
                {{form | crispy}}
                <button type = "submit" class = "btn btn-danger"> Login </button>
             </form>
        </div>
    </div>





{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <h3>Sign Up Here! </h3>
            <br>   
            <form method = "post" > 
                {% csrf_token %}
                {{form | crispy}}
                <button type = "submit" class = "btn btn-danger"> Sign Up </button>
             </form>
        </div>
    </div>




{% endblock body %}